name: Publish to npm

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.1.8"

      - name: Verify Bun installation
        run: bun --version # 验证 Bun 是否安装成功

      - name: Install dependencies
        run: bun install

      - name: Build project with Bun
        run: bun run build

      - name: remove node_modules
        run: rm -rf node_modules

      # - name: show current files
      #   run: ls -R .

      - name: Publish to npm
        continue-on-error: true
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish
